modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPLv3.0"
issueTrackerURL = "https://github.com/JoniCraftHD/luna/issues"

[[mods]]
modId = "gtsia"
version = "0.1.0"
displayName = "GT: Stuck in Abyss"
displayURL = ""
logoFile = "icon.png"
authors = "JoniCraftHD"
description = '''
GT: Stuck in Abyss - A GregTech CEu Core Mod
'''

[[dependencies.gtsia]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtsia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtsia]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

